/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteAuthRouteImport } from './routes/_site/auth'
import { Route as SiteBecomeADistributorRouteImport } from './routes/_site/become-a-distributor'
import { Route as SiteBecomeAStockistRouteImport } from './routes/_site/become-a-stockist'
import { Route as SiteBundlesRouteImport } from './routes/_site/bundles'
import { Route as SiteCartRouteImport } from './routes/_site/cart'
import { Route as SiteDealsRouteImport } from './routes/_site/deals'
import { Route as SiteEducationRouteImport } from './routes/_site/education'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteFindYourFitRouteImport } from './routes/_site/find-your-fit'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteResetPasswordRouteImport } from './routes/_site/reset-password'
import { Route as SiteShopRouteImport } from './routes/_site/shop'
import { Route as SiteSizeGuideRouteImport } from './routes/_site/size-guide'
import { Route as SiteStoreLocationRouteImport } from './routes/_site/store-location'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteTrackRouteImport } from './routes/_site/track'
import { Route as AdminDashRouteImport } from './routes/admin/_dash'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as SiteAccountIndexRouteImport } from './routes/_site/account.index'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'
import { Route as SiteCheckoutIndexRouteImport } from './routes/_site/checkout.index'
import { Route as SiteCheckoutCallbackRouteImport } from './routes/_site/checkout.callback'
import { Route as SiteProductsSlugRouteImport } from './routes/_site/products.$slug'
import { Route as AdminDashIndexRouteImport } from './routes/admin/_dash/index'
import { Route as AdminDashCategoriesRouteImport } from './routes/admin/_dash/categories'
import { Route as AdminDashCustomersRouteImport } from './routes/admin/_dash/customers'
import { Route as AdminDashEnquiriesRouteImport } from './routes/admin/_dash/enquiries'
import { Route as AdminDashPriceListRouteImport } from './routes/admin/_dash/price-list'
import { Route as AdminDashSettingsRouteImport } from './routes/admin/_dash/settings'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as SiteAccountOrdersIdRouteImport } from './routes/_site/account.orders.$id'
import { Route as AdminDashOrdersIndexRouteImport } from './routes/admin/_dash/orders.index'
import { Route as AdminDashOrdersIdRouteImport } from './routes/admin/_dash/orders.$id'
import { Route as AdminDashProductsIndexRouteImport } from './routes/admin/_dash/products.index'
import { Route as AdminDashProductsIdRouteImport } from './routes/admin/_dash/products.$id'
import { Route as AdminDashProductsNewRouteImport } from './routes/admin/_dash/products.new'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthRoute = SiteAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBecomeADistributorRoute = SiteBecomeADistributorRouteImport.update({
  id: '/become-a-distributor',
  path: '/become-a-distributor',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBecomeAStockistRoute = SiteBecomeAStockistRouteImport.update({
  id: '/become-a-stockist',
  path: '/become-a-stockist',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBundlesRoute = SiteBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDealsRoute = SiteDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEducationRoute = SiteEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFindYourFitRoute = SiteFindYourFitRouteImport.update({
  id: '/find-your-fit',
  path: '/find-your-fit',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResetPasswordRoute = SiteResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSizeGuideRoute = SiteSizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoreLocationRoute = SiteStoreLocationRouteImport.update({
  id: '/store-location',
  path: '/store-location',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrackRoute = SiteTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => SiteRoute,
} as any)
const AdminDashRoute = AdminDashRouteImport.update({
  id: '/admin/_dash',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAccountIndexRoute = SiteAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutIndexRoute = SiteCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutCallbackRoute = SiteCheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsSlugRoute = SiteProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminDashIndexRoute = AdminDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashCategoriesRoute = AdminDashCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashCustomersRoute = AdminDashCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashEnquiriesRoute = AdminDashEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashPriceListRoute = AdminDashPriceListRouteImport.update({
  id: '/price-list',
  path: '/price-list',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashSettingsRoute = AdminDashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashRoute,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAccountOrdersIdRoute = SiteAccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => SiteRoute,
} as any)
const AdminDashOrdersIndexRoute = AdminDashOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashOrdersIdRoute = AdminDashOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashProductsIndexRoute = AdminDashProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashProductsIdRoute = AdminDashProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashProductsNewRoute = AdminDashProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminDashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/auth': typeof SiteAuthRoute
  '/become-a-distributor': typeof SiteBecomeADistributorRoute
  '/become-a-stockist': typeof SiteBecomeAStockistRoute
  '/bundles': typeof SiteBundlesRoute
  '/cart': typeof SiteCartRoute
  '/deals': typeof SiteDealsRoute
  '/education': typeof SiteEducationRoute
  '/faq': typeof SiteFaqRoute
  '/find-your-fit': typeof SiteFindYourFitRoute
  '/privacy': typeof SitePrivacyRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/shop': typeof SiteShopRoute
  '/size-guide': typeof SiteSizeGuideRoute
  '/store-location': typeof SiteStoreLocationRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/admin': typeof AdminDashRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/checkout/callback': typeof SiteCheckoutCallbackRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/admin/categories': typeof AdminDashCategoriesRoute
  '/admin/customers': typeof AdminDashCustomersRoute
  '/admin/enquiries': typeof AdminDashEnquiriesRoute
  '/admin/price-list': typeof AdminDashPriceListRoute
  '/admin/settings': typeof AdminDashSettingsRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/account/': typeof SiteAccountIndexRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/checkout/': typeof SiteCheckoutIndexRoute
  '/admin/': typeof AdminDashIndexRoute
  '/account/orders/$id': typeof SiteAccountOrdersIdRoute
  '/admin/orders/$id': typeof AdminDashOrdersIdRoute
  '/admin/products/$id': typeof AdminDashProductsIdRoute
  '/admin/products/new': typeof AdminDashProductsNewRoute
  '/admin/orders/': typeof AdminDashOrdersIndexRoute
  '/admin/products/': typeof AdminDashProductsIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/auth': typeof SiteAuthRoute
  '/become-a-distributor': typeof SiteBecomeADistributorRoute
  '/become-a-stockist': typeof SiteBecomeAStockistRoute
  '/bundles': typeof SiteBundlesRoute
  '/cart': typeof SiteCartRoute
  '/deals': typeof SiteDealsRoute
  '/education': typeof SiteEducationRoute
  '/faq': typeof SiteFaqRoute
  '/find-your-fit': typeof SiteFindYourFitRoute
  '/privacy': typeof SitePrivacyRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/shop': typeof SiteShopRoute
  '/size-guide': typeof SiteSizeGuideRoute
  '/store-location': typeof SiteStoreLocationRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/checkout/callback': typeof SiteCheckoutCallbackRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/admin/categories': typeof AdminDashCategoriesRoute
  '/admin/customers': typeof AdminDashCustomersRoute
  '/admin/enquiries': typeof AdminDashEnquiriesRoute
  '/admin/price-list': typeof AdminDashPriceListRoute
  '/admin/settings': typeof AdminDashSettingsRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/account': typeof SiteAccountIndexRoute
  '/blog': typeof SiteBlogIndexRoute
  '/checkout': typeof SiteCheckoutIndexRoute
  '/admin': typeof AdminDashIndexRoute
  '/account/orders/$id': typeof SiteAccountOrdersIdRoute
  '/admin/orders/$id': typeof AdminDashOrdersIdRoute
  '/admin/products/$id': typeof AdminDashProductsIdRoute
  '/admin/products/new': typeof AdminDashProductsNewRoute
  '/admin/orders': typeof AdminDashOrdersIndexRoute
  '/admin/products': typeof AdminDashProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/auth': typeof SiteAuthRoute
  '/_site/become-a-distributor': typeof SiteBecomeADistributorRoute
  '/_site/become-a-stockist': typeof SiteBecomeAStockistRoute
  '/_site/bundles': typeof SiteBundlesRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/deals': typeof SiteDealsRoute
  '/_site/education': typeof SiteEducationRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/find-your-fit': typeof SiteFindYourFitRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/reset-password': typeof SiteResetPasswordRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/size-guide': typeof SiteSizeGuideRoute
  '/_site/store-location': typeof SiteStoreLocationRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/track': typeof SiteTrackRoute
  '/admin/_dash': typeof AdminDashRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/checkout/callback': typeof SiteCheckoutCallbackRoute
  '/_site/products/$slug': typeof SiteProductsSlugRoute
  '/admin/_dash/categories': typeof AdminDashCategoriesRoute
  '/admin/_dash/customers': typeof AdminDashCustomersRoute
  '/admin/_dash/enquiries': typeof AdminDashEnquiriesRoute
  '/admin/_dash/price-list': typeof AdminDashPriceListRoute
  '/admin/_dash/settings': typeof AdminDashSettingsRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/_site/account/': typeof SiteAccountIndexRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/checkout/': typeof SiteCheckoutIndexRoute
  '/admin/_dash/': typeof AdminDashIndexRoute
  '/_site/account/orders/$id': typeof SiteAccountOrdersIdRoute
  '/admin/_dash/orders/$id': typeof AdminDashOrdersIdRoute
  '/admin/_dash/products/$id': typeof AdminDashProductsIdRoute
  '/admin/_dash/products/new': typeof AdminDashProductsNewRoute
  '/admin/_dash/orders/': typeof AdminDashOrdersIndexRoute
  '/admin/_dash/products/': typeof AdminDashProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/auth'
    | '/become-a-distributor'
    | '/become-a-stockist'
    | '/bundles'
    | '/cart'
    | '/deals'
    | '/education'
    | '/faq'
    | '/find-your-fit'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/size-guide'
    | '/store-location'
    | '/terms'
    | '/track'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/callback'
    | '/products/$slug'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/price-list'
    | '/admin/settings'
    | '/api/paystack/webhook'
    | '/account/'
    | '/blog/'
    | '/checkout/'
    | '/admin/'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/auth'
    | '/become-a-distributor'
    | '/become-a-stockist'
    | '/bundles'
    | '/cart'
    | '/deals'
    | '/education'
    | '/faq'
    | '/find-your-fit'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/size-guide'
    | '/store-location'
    | '/terms'
    | '/track'
    | '/admin/login'
    | '/'
    | '/blog/$slug'
    | '/checkout/callback'
    | '/products/$slug'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/price-list'
    | '/admin/settings'
    | '/api/paystack/webhook'
    | '/account'
    | '/blog'
    | '/checkout'
    | '/admin'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/_site'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/auth'
    | '/_site/become-a-distributor'
    | '/_site/become-a-stockist'
    | '/_site/bundles'
    | '/_site/cart'
    | '/_site/deals'
    | '/_site/education'
    | '/_site/faq'
    | '/_site/find-your-fit'
    | '/_site/privacy'
    | '/_site/reset-password'
    | '/_site/shop'
    | '/_site/size-guide'
    | '/_site/store-location'
    | '/_site/terms'
    | '/_site/track'
    | '/admin/_dash'
    | '/admin/login'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/checkout/callback'
    | '/_site/products/$slug'
    | '/admin/_dash/categories'
    | '/admin/_dash/customers'
    | '/admin/_dash/enquiries'
    | '/admin/_dash/price-list'
    | '/admin/_dash/settings'
    | '/api/paystack/webhook'
    | '/_site/account/'
    | '/_site/blog/'
    | '/_site/checkout/'
    | '/admin/_dash/'
    | '/_site/account/orders/$id'
    | '/admin/_dash/orders/$id'
    | '/admin/_dash/products/$id'
    | '/admin/_dash/products/new'
    | '/admin/_dash/orders/'
    | '/admin/_dash/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminDashRoute: typeof AdminDashRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth': {
      id: '/_site/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof SiteAuthRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/become-a-distributor': {
      id: '/_site/become-a-distributor'
      path: '/become-a-distributor'
      fullPath: '/become-a-distributor'
      preLoaderRoute: typeof SiteBecomeADistributorRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/become-a-stockist': {
      id: '/_site/become-a-stockist'
      path: '/become-a-stockist'
      fullPath: '/become-a-stockist'
      preLoaderRoute: typeof SiteBecomeAStockistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bundles': {
      id: '/_site/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof SiteBundlesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/deals': {
      id: '/_site/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof SiteDealsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/education': {
      id: '/_site/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof SiteEducationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/find-your-fit': {
      id: '/_site/find-your-fit'
      path: '/find-your-fit'
      fullPath: '/find-your-fit'
      preLoaderRoute: typeof SiteFindYourFitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reset-password': {
      id: '/_site/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof SiteResetPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/size-guide': {
      id: '/_site/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SiteSizeGuideRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/store-location': {
      id: '/_site/store-location'
      path: '/store-location'
      fullPath: '/store-location'
      preLoaderRoute: typeof SiteStoreLocationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/track': {
      id: '/_site/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof SiteTrackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/_dash': {
      id: '/admin/_dash'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/account/': {
      id: '/_site/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof SiteAccountIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout/': {
      id: '/_site/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof SiteCheckoutIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout/callback': {
      id: '/_site/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof SiteCheckoutCallbackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/$slug': {
      id: '/_site/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof SiteProductsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/_dash/': {
      id: '/admin/_dash/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminDashIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/categories': {
      id: '/admin/_dash/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminDashCategoriesRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/customers': {
      id: '/admin/_dash/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminDashCustomersRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/enquiries': {
      id: '/admin/_dash/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminDashEnquiriesRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/price-list': {
      id: '/admin/_dash/price-list'
      path: '/price-list'
      fullPath: '/admin/price-list'
      preLoaderRoute: typeof AdminDashPriceListRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/settings': {
      id: '/admin/_dash/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminDashSettingsRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/account/orders/$id': {
      id: '/_site/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof SiteAccountOrdersIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/_dash/orders/': {
      id: '/admin/_dash/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminDashOrdersIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/orders/$id': {
      id: '/admin/_dash/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminDashOrdersIdRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/products/': {
      id: '/admin/_dash/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminDashProductsIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/products/$id': {
      id: '/admin/_dash/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminDashProductsIdRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/products/new': {
      id: '/admin/_dash/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminDashProductsNewRouteImport
      parentRoute: typeof AdminDashRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAuthRoute: typeof SiteAuthRoute
  SiteBecomeADistributorRoute: typeof SiteBecomeADistributorRoute
  SiteBecomeAStockistRoute: typeof SiteBecomeAStockistRoute
  SiteBundlesRoute: typeof SiteBundlesRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteDealsRoute: typeof SiteDealsRoute
  SiteEducationRoute: typeof SiteEducationRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteFindYourFitRoute: typeof SiteFindYourFitRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteResetPasswordRoute: typeof SiteResetPasswordRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteSizeGuideRoute: typeof SiteSizeGuideRoute
  SiteStoreLocationRoute: typeof SiteStoreLocationRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTrackRoute: typeof SiteTrackRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteCheckoutCallbackRoute: typeof SiteCheckoutCallbackRoute
  SiteProductsSlugRoute: typeof SiteProductsSlugRoute
  SiteAccountIndexRoute: typeof SiteAccountIndexRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteCheckoutIndexRoute: typeof SiteCheckoutIndexRoute
  SiteAccountOrdersIdRoute: typeof SiteAccountOrdersIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAuthRoute: SiteAuthRoute,
  SiteBecomeADistributorRoute: SiteBecomeADistributorRoute,
  SiteBecomeAStockistRoute: SiteBecomeAStockistRoute,
  SiteBundlesRoute: SiteBundlesRoute,
  SiteCartRoute: SiteCartRoute,
  SiteDealsRoute: SiteDealsRoute,
  SiteEducationRoute: SiteEducationRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteFindYourFitRoute: SiteFindYourFitRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteResetPasswordRoute: SiteResetPasswordRoute,
  SiteShopRoute: SiteShopRoute,
  SiteSizeGuideRoute: SiteSizeGuideRoute,
  SiteStoreLocationRoute: SiteStoreLocationRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTrackRoute: SiteTrackRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteCheckoutCallbackRoute: SiteCheckoutCallbackRoute,
  SiteProductsSlugRoute: SiteProductsSlugRoute,
  SiteAccountIndexRoute: SiteAccountIndexRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteCheckoutIndexRoute: SiteCheckoutIndexRoute,
  SiteAccountOrdersIdRoute: SiteAccountOrdersIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminDashRouteChildren {
  AdminDashCategoriesRoute: typeof AdminDashCategoriesRoute
  AdminDashCustomersRoute: typeof AdminDashCustomersRoute
  AdminDashEnquiriesRoute: typeof AdminDashEnquiriesRoute
  AdminDashPriceListRoute: typeof AdminDashPriceListRoute
  AdminDashSettingsRoute: typeof AdminDashSettingsRoute
  AdminDashIndexRoute: typeof AdminDashIndexRoute
  AdminDashOrdersIdRoute: typeof AdminDashOrdersIdRoute
  AdminDashProductsIdRoute: typeof AdminDashProductsIdRoute
  AdminDashProductsNewRoute: typeof AdminDashProductsNewRoute
  AdminDashOrdersIndexRoute: typeof AdminDashOrdersIndexRoute
  AdminDashProductsIndexRoute: typeof AdminDashProductsIndexRoute
}

const AdminDashRouteChildren: AdminDashRouteChildren = {
  AdminDashCategoriesRoute: AdminDashCategoriesRoute,
  AdminDashCustomersRoute: AdminDashCustomersRoute,
  AdminDashEnquiriesRoute: AdminDashEnquiriesRoute,
  AdminDashPriceListRoute: AdminDashPriceListRoute,
  AdminDashSettingsRoute: AdminDashSettingsRoute,
  AdminDashIndexRoute: AdminDashIndexRoute,
  AdminDashOrdersIdRoute: AdminDashOrdersIdRoute,
  AdminDashProductsIdRoute: AdminDashProductsIdRoute,
  AdminDashProductsNewRoute: AdminDashProductsNewRoute,
  AdminDashOrdersIndexRoute: AdminDashOrdersIndexRoute,
  AdminDashProductsIndexRoute: AdminDashProductsIndexRoute,
}

const AdminDashRouteWithChildren = AdminDashRoute._addFileChildren(
  AdminDashRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminDashRoute: AdminDashRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
